/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class get_hard_sate7phoneinfo_util_Base64Tool */

#ifndef _Included_get_hard_sate7phoneinfo_util_Base64Tool
#define _Included_get_hard_sate7phoneinfo_util_Base64Tool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     get_hard_sate7phoneinfo_util_Base64Tool
 * Method:    nativeEncode
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_get_hard_sate7phoneinfo_util_Base64Tool_nativeEncode
        (JNIEnv *env, jobject jobj, jbyteArray srcData, jint len);

/*
 * Class:     get_hard_sate7phoneinfo_util_Base64Tool
 * Method:    nativeDecode
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jbyteArray JNICALL Java_get_hard_sate7phoneinfo_util_Base64Tool_nativeDecode
        (JNIEnv *env, jobject jobj, jstring decodeData, jint len);

#ifdef __cplusplus
}
#endif
#endif
